BoomingTech/Piccolo

engine/CMakeLists.txt
修复 CMakeLists.txt 在 Win 下存在的问题. #9
并将添加该编译选项条件改为更精准的 `MSVC`, 还是有不少 Win 下的用户会使用 GCC 等其他编译套件(如: CLion 用户).
=> Fix CMakeLists.txt

README.md
The course name is `GAMES104` but not `gams104` in README.md file. This PR fixes the typo on it.
=> Fix typo on the course name

README.md
On Ubuntu 20.04, sudo needs to be added to execute apt command normally
=> Correct apt command

engine/source/runtime/function/render/source/vulkan_manager/context/vulkan_context.cpp
after modify, vulcan context will first rank gpu, and give score by device type (discrete gpu, integrated gpu or virtual gpu) then give a score(1000 for discrete gpu, 100 for integrated gpu and 0 for others) then sort by score.
In this case, it will first check suitability for better(discrete gpu) first. If the system has a higher scored gpu that suitable it will select the higher scored one, if the higher scored one doesn't support some fatal feature engine need, it will check lower scored gpu. Mean while, we'll get "the best"(in most cases) suitable gpu for vulkan.
=> Fix: score gpu and rank before check physical device suitability to find the best gpu for rending

engine/3rdparty/.clang-format
Disable formatting for any code under engine/3rdparty/, we should avoid controlling third party code.
=> Exclude 3rdparty/ from root clang-format config

engine/source/editor/source/editor_ui.cpp
Available fix suggestion from clangd: format string is not a string literal (potentially insecure) (fix available) [-Wformat-security].
Change example:
- change `ImGui::Text(name.c_str())` to `ImGui::Text("%s", name.c_str())`
=> Fix: format-security

engine/source/editor/source/axis.cpp, engine/source/runtime/core/math/math.cpp, engine/source/runtime/core/math/math.h, engine/source/runtime/core/math/matrix4.h, engine/source/runtime/core/math/quaternion.h, engine/source/runtime/core/math/vector2.h, engine/source/runtime/core/math/vector3.h, engine/source/runtime/core/math/vector4.h, engine/source/runtime/engine.cpp, engine/source/runtime/engine.h, engine/source/runtime/function/framework/component/camera/camera_component.cpp, engine/source/runtime/function/framework/component/camera/camera_component.h, engine/source/runtime/function/framework/component/component.h, engine/source/runtime/function/framework/component/motor/motor_component.cpp, engine/source/runtime/function/framework/level/level.cpp, engine/source/runtime/function/framework/level/level.h, engine/source/runtime/function/framework/world/world_manager.h, engine/source/runtime/function/physics/collision_detection.cpp, engine/source/runtime/function/physics/collision_detection.h, engine/source/runtime/function/scene/scene_manager.cpp, engine/source/runtime/function/scene/scene_manager.h
const before POD in function arguments is unnecessary
=> remove const before POD in function arguments

engine/source/runtime/function/render/source/vulkan_manager/context/vulkan_context.cpp
更正异常消息.
原本的消息为 `enumerate physical devices`, 但这并不是错误发生的原因. 该异常是在没有找到合适的设备时被抛出, 而不是不能获取设备数据.
因为有一些 Issues 给出了一个异常, 但是却没有给出抛出的具体位置, 给错误排查造成了一定的困惑.
=> Fix std::runtime_error message

engine/source/runtime/core/math/matrix3.h, engine/source/runtime/core/math/matrix4.h, engine/source/runtime/function/animation/utilities.h, engine/source/runtime/function/render/source/vulkan_manager/context/vulkan_context.cpp, engine/source/runtime/function/render/source/vulkan_manager/misc/upload.cpp, engine/source/runtime/function/render/source/vulkan_manager/ui_interface/editor.cpp
Fix header file missing (which would cause compile error on Fedora OS)
=> Fix header file missing (which would cause compile error on Fedora OS)

engine/shader/glsl/mesh.vert, engine/shader/glsl/mesh_directional_light_shadow.vert, engine/shader/glsl/mesh_inefficient_pick.vert, engine/shader/glsl/mesh_point_light_shadow.vert, engine/shader/include/structures.h, engine/source/runtime/function/render/include/render/vulkan_manager/vulkan_common.h, engine/source/runtime/function/render/source/vulkan_manager/passes/directional_light.cpp, engine/source/runtime/function/render/source/vulkan_manager/passes/lighting.cpp, engine/source/runtime/function/render/source/vulkan_manager/passes/point_light.cpp, engine/source/runtime/function/render/source/vulkan_manager/vulkan_global_resource.cpp, engine/source/runtime/function/render/source/vulkan_manager/vulkan_manager.cpp
=> Fix Apple M1 Crash

engine/asset/objects/character/player/components/camera/third_person.camera.json, engine/source/runtime/function/framework/component/camera/camera_component.cpp
Now the third-person camera shifts from side-to-side when rotating, which was caused by this line in 
`engine/source/runtime/function/framework/component/camera/camera_component.cpp`:
`Vector3 center_pos = parent_transform->getPosition() + Vector3::UNIT_Z * vertical_offset - 0.5f;`.
=> Fix third-person camera rotation

engine/source/editor/source/editor_ui.cpp, engine/source/runtime/function/render/source/surface_ui.cpp
Here is a quick fix to load font using DPI scaling. And it's reactive to DPI changes while the engine is running.
A brief introduction on the issue fixed https://github.com/BoomingTech/Pilot/issues/84
=> DPI awareness font scaling

engine/source/runtime/function/render/source/vulkan_manager/misc/misc.cpp
Fix directional light camera calculation
=> Fix directional light camera calculation

engine/source/runtime/core/math/vector2.h, engine/source/runtime/function/scene/scene_manager.cpp, engine/source/runtime/function/scene/scene_manager.h
1. `Vector2` class is missing a `operator[]` as `Vector3` and `Vector4` does. Also there're 3 typos in the comment.
2. In scene_manager:
https://github.com/BoomingTech/Pilot/blob/5de12a37d1709ced2d2be324ad5f7a88727bfb9b/engine/source/runtime/function/scene/scene_manager.h#L38
this function declares its parameter as `const &&`(seems strange), I suppose it should be either `const &` or `&&`?<br>
https://github.com/BoomingTech/Pilot/blob/5de12a37d1709ced2d2be324ad5f7a88727bfb9b/engine/source/runtime/function/scene/scene_manager.cpp#L678
The release function for mesh, material and skeleton binding use `auto` to get the element from a `std::deque`, which is a copy. Maybe it's better to use a reference. Also renaming the variable `handle` to `skeleton_binding_handle` to keep consistent with its …
=> More fixes

engine/source/editor/include/editor.h, engine/source/runtime/engine.h, engine/source/runtime/function/framework/world/world_manager.h, engine/source/runtime/function/input/input_system.h, engine/source/runtime/function/ui/ui_system.h, engine/source/runtime/platform/file_service/file_service.h
修正单例类的实现方式, 确保只会存在一个实例.
值得注意的是因为这些类全部没用使用 final 修饰, 所以我假设都可能被继承. 构造函数的访问限定符为 protected, 如果不会被继承的话最好使用 final 修饰并把构造函数的访问限定符改为 private.
=> Fix singleton classes

engine/source/runtime/function/render/source/vulkan_manager/passes/pick.cpp
The current 'pick' implementation uses an image barrier before the copy command, which transfers the rendered image from `VK_IMAGE_LAYOUT_UNDEFINED` to `VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL`.  According to [vk spec](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageLayout.html), doing so will cause the contents of the image’s memory to be undefined. The expected `oldLayout` is `VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL` specified in the `finalLayout` field of subpass description.
Similarly, an earlier barrier transfers the image's layout from `VK_IMAGE_LAYOUT_UNDEFINED` to `VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL`. This transition is presented again in the renderpass description.
This commit fixes #42 by correcting these layout values.
=> Fix image layout transition in 'pick' pass

engine/source/editor/source/editor_ui.cpp, engine/source/runtime/function/render/source/surface.cpp
* `GLFW_CURSOR_HIDDEN` didn't really hide the cursor
* `glfwSetInputMode` got conflict between `editor_ui.cpp` and `surface_io.h`
=> [Fixed] Cursor twinkling in editor mode

engine/source/editor/source/editor_ui.cpp, engine/source/runtime/function/render/include/render/surface.h, engine/source/runtime/function/render/source/surface_ui.cpp
As the title, there is a button overlapped by other GUI elements while resolution scale is larger than 100%.  #92 
Case `ImGui::Indent` also need consider DPI scale on Windows. 
However, the real problem might be GLFW. It's using virtual resolution on macOS but real pixel resolution on Windows.
Eventually, it will have side-effect on ImGui.
Tested on:
Windows 10 Pro 21h2
macOS BIg sur 11.6.5
Not tested on Linux.
=> Fix overlapped button, ImGui::Indent should also consider DPI scale

.gitignore
添加了 Visual Studio 的个性化配置文件 并 根据IDE进行了简单的分类.
值得注意的是:
- `CMakeSettings.json` 文件是 Visual Studio 下 CMake 项目会生成的配置文件, 因此归类为 Visual Studio 的配置文件.
- CLion 中可能只有 `.idea` 目录是需要忽略的, 不过这个 PR 没有对其进行修改.
=> Add Visual Studio configuration file to .gitignore

engine/source/runtime/function/render/source/vulkan_manager/context/vulkan_context.cpp
The problem is described in this link: [vkEnumeratePhysicalDevices error](https://stackoverflow.com/questions/68109171/vkenumeratephysicaldevices-not-finding-all-gpus).
Tested on the following three platforms:
- only AMD graphics card
- only NVIDIA graphics card
- AMD CPU with graphics card and NVIDIA graphics card
=> Disable AMD switchable graphics device to avoid enumerating error

engine/source/editor/source/editor_ui.cpp
Better support for high resolution monitor.
=> [Optimize] Fix editor camera is too sensitive for 4k monitor/screen

engine/source/runtime/engine.h, engine/source/runtime/function/framework/world/world_manager.h, engine/source/runtime/function/scene/scene_manager.h, engine/source/runtime/function/scene/scene_object.h, engine/source/runtime/function/ui/ui_system.h, engine/source/runtime/resource/config_manager/config_manager.h
- 因为 PublicSingleton 是一个不可拷贝的类, 因此其子类不需要再显示声明拷贝构造函数和赋值构造函数删除.
- SceneObject 中的部分函数实现和默认的行为无异, 因此删去.
- 防止单例类 ConfigManager 创建多个实例.
=> Remove unnecessary code + Fix config_manager.h

engine/source/runtime/core/meta/reflection/reflection.h, engine/source/runtime/function/character/character.cpp, engine/source/runtime/function/framework/component/animation/animation_component.cpp, engine/source/runtime/function/framework/component/animation/animation_component.h, engine/source/runtime/function/framework/component/camera/camera_component.cpp, engine/source/runtime/function/framework/component/camera/camera_component.h, engine/source/runtime/function/framework/component/component.h, engine/source/runtime/function/framework/component/mesh/mesh_component.cpp, engine/source/runtime/function/framework/component/mesh/mesh_component.h, engine/source/runtime/function/framework/component/motor/motor_component.cpp, engine/source/runtime/function/framework/component/motor/motor_component.h, engine/source/runtime/function/framework/component/rigidbody/rigidbody_component.cpp, engine/source/runtime/function/framework/component/rigidbody/rigidbody_component.h, engine/source/runtime/function/framework/component/transform/transform_component.h, engine/source/runtime/function/framework/level/level.cpp, engine/source/runtime/function/framework/object/object.cpp, engine/source/runtime/function/framework/object/object.h, engine/source/runtime/resource/asset_manager/asset_manager.cpp, engine/source/runtime/resource/res_type/components/animation.h, engine/source/runtime/resource/res_type/components/camera.cpp, engine/source/runtime/resource/res_type/components/camera.h
1. removed tick in editor check from each component, check in object tick
2. each component now holds its runtime component data, unified the name of component data to component_name_res
3. removed useless destroy()
4. move deep copy of component data from component constructor to component data class  copy constructor (WIP)
=> Refactor for Documentation 1

build_linux.sh
Allow using ninja on default if ninja is found. It's enabled on the Linux platform by the build_linux.sh.
Ninja is much faster than Unix Make. It reduced the build time from 63.96 seconds to 12.14 seconds,
which means a 5x times speedup.
=> Allow using ninja on default if ninja is found on Linux platform

build_linux.sh
In my last PR, I delete "-j$(nproc)" by accident and it will let the Unix Make use only one thread, which is more slower... I have fixed this and also corrected the inconsistency between code and description. Sorry about that!
=> Add `-j$(nproc)` to the build command

README.md, build_compile_db.bat, scripts/generate_compile_db.bat
This PR is helpful for developers using Emacs as code editor. 
When using `lsp-mode` with `clangd` language server, `compile_commands.json` is required to find the includes properly. (per https://emacs-lsp.github.io/lsp-mode/tutorials/CPP-guide/)
* Added a .bat script builds and copys `compile_commands.json`
* Updated doc accordingly
----
screenshot:
=> Add the building script for compile db

engine/source/runtime/function/framework/level/level.cpp
修复了对 `std::make_shared` 的错误处理. `std::make_shared` 无法分配时会抛出异常, 而不是返回 `nullptr`.
> May throw [std::bad_alloc](https://en.cppreference.com/w/cpp/memory/new/bad_alloc) or any exception thrown by the constructor of T.
参考: <https://en.cppreference.com/w/cpp/memory/shared_ptr/make_shared>
=> Fix level.cpp

engine/source/runtime/function/render/render_resource.cpp
修复color grading纹理mipmap级别问题（只需一层mipmap，否则会导致颜色断层）
=> Fix color grading texture's mipmap level bug

engine/3rdparty/CMakeLists.txt, engine/CMakeLists.txt, engine/asset/objects/environment/floor/floor.object.json, engine/source/runtime/CMakeLists.txt, engine/source/runtime/engine.cpp, engine/source/runtime/function/controller/character_controller.cpp, engine/source/runtime/function/framework/component/rigidbody/rigidbody_component.cpp, engine/source/runtime/function/framework/level/level.cpp, engine/source/runtime/function/framework/level/level.h, engine/source/runtime/function/framework/world/world_manager.cpp, engine/source/runtime/function/framework/world/world_manager.h, engine/source/runtime/function/global/global_context.cpp, engine/source/runtime/function/global/global_context.h, engine/source/runtime/function/physics/jolt/utils.cpp, engine/source/runtime/function/physics/jolt/utils.h, engine/source/runtime/function/physics/physics_aabb_shape.h, engine/source/runtime/function/physics/physics_actor.h, engine/source/runtime/function/physics/physics_config.h, engine/source/runtime/function/physics/physics_manager.cpp, engine/source/runtime/function/physics/physics_manager.h, engine/source/runtime/function/physics/physics_obb_shape.h, engine/source/runtime/function/physics/physics_scene.cpp, engine/source/runtime/function/physics/physics_scene.h, engine/source/runtime/function/physics/physics_shape_base.h, engine/source/runtime/function/physics/physics_sphere_shape.h, engine/source/runtime/function/physics/physics_system.h, engine/source/runtime/function/render/render_system.cpp, engine/source/runtime/function/render/render_system.h
Integrate Jolt Physics Engine,
- RigidBody creation and destroy (only support static object currently)
- Scene Query: raycast, sweep, overlap 
- Simulation
- Physics Debug Renderer: (work in progress)
=> Integrate Jolt Physics Engine

engine/source/runtime/core/math/random.h
Fix random engine class namespace typo
=> Fix namespace typo

engine/source/runtime/core/base/hash.h, engine/source/runtime/function/physics/collision_detection.h, engine/source/runtime/function/render/render_type.h
hash_combine 实现来源: <https://www.boost.org/doc/libs/1_62_0/doc/html/hash.html>
=> Add hash_combine

engine/source/runtime/function/render/passes/directional_light_pass.cpp, engine/source/runtime/function/render/passes/main_camera_pass.cpp, engine/source/runtime/function/render/passes/pick_pass.cpp, engine/source/runtime/function/render/passes/point_light_pass.cpp, engine/source/runtime/function/render/render_common.h, engine/source/runtime/function/render/render_scene.cpp
=> Reduce unnecessary copies of memory data to improve rendering performance

engine/source/editor/source/editor_ui.cpp
While adding bool to a reflectable field, I discover that the editor UI won't show a bool field, so add a check box for bool field in editor UI
=> feature: Add checkbox for bool field in editor ui

engine/source/runtime/function/render/render_pipeline.cpp
forwardRender()函数中创建fxaa_pass时错误使用了m_tone_mapping_pass.get()
=> render_pipeline.cpp中forwardRender()函数，创建fxaa_pass时错误使用了m_tone_mapping_pass.get()

engine/source/runtime/core/math/math.cpp, engine/source/runtime/core/math/math.h, engine/source/runtime/function/render/passes/directional_light_pass.cpp, engine/source/runtime/function/render/render_helper.cpp
阴影的正交矩阵计算的Z值范围是[-1,1], 改成 [0,1]
=> 修复直接光照下阴影显示不全

engine/source/runtime/function/framework/level/level.cpp, engine/source/runtime/function/particle/emitter_id_allocator.cpp, engine/source/runtime/function/particle/emitter_id_allocator.h, engine/source/runtime/function/render/passes/particle_pass.cpp, engine/source/runtime/function/render/passes/particle_pass.h, engine/source/runtime/function/render/render_system.cpp
修复关卡重新加载导致的闪退。
1. 删除未使用的指针，会导致销毁时崩溃
2. 关卡重新时重置 particle id 分配器计数
=> fix gpu particle level reload logic

build_macos.sh, engine/3rdparty/CMakeLists.txt
新版本的Clang引入了对未限定的move()等操作的检查，导致JoltPhysics库编译产生大量错误失败。见：<https://reviews.llvm.org/D119670>
当前版本的JoltPhysics使用了大量using namespace std;，在不修改JoltPhysics源代码的情况下，在CMake引入依赖时增加`-Wno-unqualified-std-cast-call`编译选项关闭告警对代码产生的破坏性较小。
=> Fix JoltPhysics compile error on later clang and Xcode

engine/source/editor/source/axis.cpp
将
size_t vertex_data_size = ((2 * segments + 8) * 3 + 8) * stride;
修改为：
size_t vertex_data_size = ((2 * segments + 8) * 3) * stride;
=> 编辑器模式下物体缩放轴的vertex_data_size计算中多加了8，有一个多余的白色方块

engine/source/editor/source/axis.cpp
This reverts commit 89f1dddc105c0cbe7c33313a4cfe809d36f08947.
这次提交导致了崩溃：https://github.com/BoomingTech/Piccolo/commit/89f1dddc105c0cbe7c33313a4cfe809d36f08947
为了避免别的同学遇到，先revert掉，原问题需再分析
=> Revert "编辑器模式下物体缩放轴的vertex_data_size计算中多加了8，有一个多余的白色方块"

engine/3rdparty/CMakeLists.txt
Add JointPhysics local warning option to avoid -Werro(/WX) pollute
=> make JointPhysics dont treat warning as error when compile
