BoomingTech/Piccolo

- engine/source/editor/source/editor_ui.cpp
- engine/source/runtime/core/math/transform.h
- engine/source/runtime/core/math/vector3.h
- engine/source/runtime/function/animation/utilities.cpp
- engine/source/runtime/function/physics/collision_detection.cpp
fix some compile warning and comment typo
> fix compile warning

- engine/source/editor/source/editor_ui.cpp
- engine/source/runtime/function/render/source/surface_ui.cpp
Add high dpi support (to be test on macOS and window)
> Add high dpi support

- .github/workflows/build_linux.yml
- .github/workflows/build_macos.yml
- README.md
> add github workflows

- .github/workflows/build_macos.yml
- README.md
> rename MacOS to masOS

- engine/asset/objects/character/player/components/camera/third_person.camera.json
- engine/source/runtime/function/framework/component/camera/camera_component.cpp
Optimize third person camera settings and calculation
> Optimize third person camera settings and calculation

- .github/workflows/build_macos.yml
- README.md
- build_macOS.sh
> feature: add macOS script too

- engine/source/runtime/core/math/math.cpp
- engine/source/runtime/core/math/math.h
- engine/source/runtime/core/math/quaternion.cpp
- engine/source/runtime/core/math/quaternion.h
- engine/source/runtime/core/math/vector2.h
- engine/source/runtime/core/math/vector3.h
- engine/source/runtime/function/render/source/vulkan_manager/ui_interface/editor.cpp
1. ``std::max``  ``std::min`` ``std::clamp`` is generic
2.  ``std::hypot`` is better than ``sqrt(sqr())``
> Refactor: Use STL

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yaml
- .github/ISSUE_TEMPLATE/feature_request.md
Add the ISSUE_TEMPLATE files, including bug_report and feature_request templates.
> Add ISSUE_TEMPLATE

- .github/workflows/build_windows.yml
- README.md
add the build windows workflow, the default compiler is vs2022
> Add build windows workflow

- engine/source/editor/source/editor_ui.cpp
The ``DrawVecControl`` function is added to make the vector UI more beautiful and more unity like.
> ✨ feat: Beautify transform component UI

- README.md
- engine/source/runtime/core/math/random.h
- engine/source/runtime/function/framework/world/world_manager.h
- engine/source/runtime/function/input/input_system.h
Remove tbb lib dependence on Linux platform
> Remove tbb lib dependence

- engine/source/runtime/function/controller/character_controller.cpp
- engine/source/runtime/function/controller/character_controller.h
给类Pilot::Controller添加了虚析构函数，防止内存泄漏。
> Add virtual destructor for class Pilot::Controller

- engine/source/editor/source/editor_ui.cpp
Support the combination of various moving directions, like going right and up at the same time.
> [Updated] A better editor camera controlling

- engine/source/runtime/function/framework/world/world_manager.cpp
> Use STL algorithm

- engine/source/editor/source/main.cpp
- engine/source/runtime/engine.cpp
修正了单例类的使用方式, 原本的用法看上去有些吓人. (继承了, 但是没有完全继承)
> Remove unnecessary code

- engine/CMakeLists.txt
Update CMakeLists.txt to set the startup project PilotEditor in Visual Studio
> Set the startup project PilotEditor in Visual Studio

- engine/shader/include/mesh_lighting.h
- engine/shader/include/mesh_lighting.inl
- engine/source/runtime/function/render/source/vulkan_manager/passes/main_camera.cpp
1. Fix errors in "F_SchlickR"
2. Fix errors in subpass dependency
> Fix Rendering Bug

- engine/source/runtime/function/render/include/render/vulkan_manager/vulkan_manager.h
- engine/source/runtime/function/render/source/vulkan_manager/context/vulkan_context.cpp
- engine/source/runtime/function/render/source/vulkan_manager/misc/setup.cpp
- engine/source/runtime/function/render/source/vulkan_manager/vulkan_manager.cpp
> Fix variable naming: m_enable_debug_untils_label -> m_enable_debug_utils_label

- engine/source/editor/source/editor_file_service.cpp
- engine/source/editor/source/editor_ui.cpp
- engine/source/runtime/function/animation/utilities.cpp
> Passing std::string by reference

- engine/source/editor/include/editor_ui.h
- engine/source/editor/source/editor_ui.cpp
> Editor GUI improved.

- engine/source/editor/source/editor_scene_manager.cpp
Set transform component of selected object dirty in Editor Mode
> set transform component of selected object dirty

- engine/source/runtime/function/render/rhi/vulkan/vulkan_rhi.h
> FIX bug : macos validation layer error message

- engine/source/runtime/core/meta/json.h
- engine/source/runtime/core/meta/meta_example.cpp
- engine/source/runtime/core/meta/reflection/reflection.cpp
- engine/source/runtime/core/meta/reflection/reflection.h
- engine/source/runtime/core/meta/reflection/reflection_register.cpp
- engine/source/runtime/core/meta/reflection/reflection_register.h
- engine/source/runtime/core/meta/serializer/serializer.cpp
- engine/source/runtime/core/meta/serializer/serializer.h
- engine/source/runtime/engine.cpp
- engine/source/runtime/resource/asset_manager/asset_manager.h
- engine/template/allReflectionFile.mustache
- engine/template/allSerializer.ipp.mustache
- engine/template/commonReflectionFile.mustache
- engine/template/commonSerializerGenFile.mustache
> Reflection Code Rename

- engine/source/meta_parser/CMakeLists.txt
- engine/source/meta_parser/parser/generator/reflection_generator.cpp
- engine/source/meta_parser/parser/generator/reflection_generator.h
- engine/source/meta_parser/parser/meta/meta_utils.cpp
- engine/source/meta_parser/parser/meta/meta_utils.h
- engine/template/allReflectionFile.mustache
- engine/template/commonReflectionFile.mustache
> modify type wrapper register.

- engine/source/runtime/CMakeLists.txt
> fix: fix a typo

- engine/asset/objects/character/player/player.object.json
- engine/source/meta_parser/parser/generator/generator.cpp
- engine/source/meta_parser/parser/generator/generator.h
- engine/source/meta_parser/parser/generator/reflection_generator.cpp
- engine/source/meta_parser/parser/generator/serializer_generator.cpp
- engine/source/meta_parser/parser/language_types/class.cpp
- engine/source/meta_parser/parser/language_types/class.h
- engine/source/meta_parser/parser/language_types/method.cpp
- engine/source/meta_parser/parser/language_types/method.h
- engine/source/meta_parser/parser/meta/meta_data_config.h
- engine/source/runtime/core/meta/reflection/reflection.cpp
- engine/source/runtime/core/meta/reflection/reflection.h
- engine/source/runtime/function/framework/component/lua/lua_component.cpp
- engine/source/runtime/function/framework/component/lua/lua_component.h
- engine/source/runtime/function/framework/component/motor/motor_component.cpp
- engine/source/runtime/function/framework/component/motor/motor_component.h
- engine/template/commonReflectionFile.mustache
The commits adding get set and simple function reflection in 2nd code review video.
watch video：【【自研开源游戏引擎】Piccolo源码反射系统解读，全网最适合入门的引擎教程】 https://www.bilibili.com/video/BV1UW4y1g7Mr
> simple function reflection 
